#!/bin/sh
#
# File: autorm
# Version: 5.2019.0
# Author: BreadyX
#
# Simple shell script that handles removing unused packages/flatpaks. (DNF VERSION)
#

VERSION="5.2019.0"

# Function that checks for input
_check_input()
{ 
	if [ -z "$1" ]; then # check if not --assumeyes
		printf "Is this ok? [Y/n]: "
		read -r INPUT
		if [ "$(echo $INPUT | tr [:upper] [:lower])" = "n" ]; then 
			printf "Operation aborted by user\n"
			return 1
		fi
	else
		# Check for user error
		if [ "$1" != "--assumeyes" ]; then 
			printf "Invalid option $1. See 'autorm --help'\n"
			return 1
		fi
	fi
}

_pac_rm()
{ # Function to remove orphaned dnf packages
	printf "+++ DNF +++\n"
	printf "Searching for orphaned packages...\n"

	# Get a list of orphaned packages
	PACKS="$(dnf list autoremove --quiet | sed '1d' | awk '{print $1}')" 
	[ -z "$PACKS" ] && { echo "No orphaned packages..."; return 0; }
	printf "You got this orphaned packages:\n%s\n" "$PACKS"

	_check_input "$1" || return $?
	dnf autoremove --assumeyes --quiet	
}

_flatpak_rm()
{
	# Check if flatpak is installed
	flatpak --version > /dev/null 2>&1 || { 
		[ "$2" != "-t" ] && printf "Flatpak is not installed\n"
		return 1
	}
	
	# Flatpak hasn't got a way to list all unused packages
	
	printf "+++ FLATPAK +++\n"
	_check_input "$1" || return $?
	flatpak remove --unused --assumeyes
}

# Function that removes orphaned snap packages 
_snap_rm()
{ 
	# Check if snapd is installed
	snap --version >/dev/null 2>&1 || { 
		[ "$2" != "-t" ] && printf "Snap is not installed\n"
		return 1
	} 

	# Get list of all packages
	printf "+++ SNAP +++\n"
	PACKS="$(snap list --all | awk '/disabled/{print $1, $3}')"
	printf "You got this orphaned packages:\n%s\n" "$PACKS"

	# Ask for confiramtio and delete
	_check_input "$1" || return $?
	echo "$PACKS" | while read -r snapname revision; do # Remove packages
		snap remove "$snapname" --revision="$revision"
	done
}

#
# MAIN
#
if [ "$(id -u)" -ne 0 ]; then 
	printf "Please run as root\n"
	exit
fi

case $1 in
	"all"|"")
		_pac_rm "$2" || exit $?
		_flatpak_rm "$2" "-t" || exit $?
		_snap_rm "$2" "-t" || exit $?		
		;;
	"packs")
		_pac_rm "$2"
		exit $?
		;;
	"flatpak")
		_flatpak_rm "$2" 
		exit $?
		;;
	"snap")
		_snap_rm "$2" 
		exit $?
		;;
	"--help")
		cat << EOF
autorm [--help] [--version] [<command>] [--assumeyes]

Removes unused programs. It supports the system package manager, flatpak and snap.

If no command is given, the program defaults to 'all'

COMMANDS:
	packs		remove only orphaned packages with pacman
	flatpak		remove only unused flatpaks (if flatpak is not installed will return error)
	snap		remove only unused snaps (if snapd is not installed will return error)
	all			remove every orphan (if possible)

OPTIONS:
	--help 		Display this message
	--version	Display info about version
	--assumeyes Don't ask for any confirmation

autorm - BreadyX's utils (BXU). Version $VERSION
This program has been written by BreadyX, contacts (for bug reports and other):
    Github profile:     https://github.com/BreadyX
    GitHub repo (BXU):  https://github.com/BreadyX/bxu
EOF
		exit 0
		;;
	"--version")
		cat << EOF
autorm - BreadyX's utils (BXU). Version $VERSION
This program has been written by BreadyX, contacts (for bug reports and other):
    Github profile:     https://github.com/BreadyX
    GitHub repo (BXU):  https://github.com/BreadyX/bxu
EOF
		;;
	"*")
		printf "Invalid syntax, see 'autorm --help' for usage\n"
		exit 1
		;;
esac
