#!/bin/sh
#
# File: gitsum
# Version: 5.2019.0
# Author: BreadyX
#
# Small script that prints formatted information about the git repository opened
#

VERSION='5.2019.0'

makeprompt()
{
	# Define variables
	branch=""
	stash=
	not_pushed=
	not_tracked=
	# Assign variables
	if [ -n "$(git branch)" ]; then
		branch="$(git branch | grep "\*" | cut -d " " -f2)"
	fi
	[ -n "$(git stash list)" ] && stash="$"
	[ -n "$(git remote)" ] && [ -n "$(git log origin/"$branch"..HEAD)" ] && not_pushed="+"
	[ -n "$(git status -u -s)" ] && not_tracked="*"
	printf " %s; [%s%s%s]" "$branch" "$not_tracked" "$not_pushed" "$stash"
}

recurse() 
{
	RECURSE="$1"
	TOCHECK=""
	if [ -d "./.git" ]; then
		makeprompt
	else
		for i in $(seq 1 "$RECURSE"); do
			if [ -d "$TOCHECK.git" ]; then
				makeprompt
				break
			fi
			TOCHECK="../$TOCHECK"
		done
	fi
}

seq --version >/dev/null 2>&1 || {
	printf "seq is not installed! Please install seq to make gitsum work.\n" >&2
	exit 1
}

case $1 in
	"--help")
		cat << EOF
gitsum [--help] [--version] [<number>]

Simple script that formats a quick summary about git repositories. The script 
looks for a '.git' directory in directories going up to <number> levels, where
<number> is an integer between 0 and 99.

If <number> is not given, the program defaults to 1.

OPTIONS:
	--help		Display this message
	--version	Display version info


gitsum - BreadyX's utils (BXU). Version $VERSION
This program has been written by BreadyX, contacts (for bug reports and other):
    Github profile:     https://github.com/BreadyX
    GitHub repo (BXU):  https://github.com/BreadyX/bxu
EOF
		;;
	"--version")
		cat << EOF
gitsum - BreadyX's utils (BXU). Version $VERSION
This program has been written by BreadyX, contacts (for bug reports and other):
    Github profile:     https://github.com/BreadyX
    GitHub repo (BXU):  https://github.com/BreadyX/bxu
EOF
	;;
	[0-9]|[0-9][0-9])
		recurse "$1"
		exit 0
		;;
	"")
		recurse "1"
		exit 0
		;;
	*)
		echo "Invalid option, for help use gitsum --help" >&2
		exit 1
		;;
esac
